name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          sudo docker build -t mlearning .
          sudo docker run -d -p 8000:8000 mlearning
        env:
          GITHUB_TOKEN: ${{ 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 }}
